# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='products.proto',
  package='products',
  syntax='proto3',
  serialized_pb=_b('\n\x0eproducts.proto\x12\x08products\"o\n\x0cQuoteRequest\x12\x0e\n\x06rfq_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61\x63\x63_id\x18\x02 \x01(\x05\x12\x13\n\x0bproduct_num\x18\x03 \x01(\x05\x12\x18\n\x10product_category\x18\x04 \x01(\t\x12\x10\n\x08quantity\x18\x05 \x01(\x05\"A\n\nQuoteReply\x12\x12\n\nunit_price\x18\x01 \x01(\x01\x12\x1f\n\x17price_validation_period\x18\x02 \x01(\t\"\x7f\n\x07Product\x12\x13\n\x0bproduct_num\x18\x01 \x01(\x05\x12\x18\n\x10product_category\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x1f\n\x17price_validation_period\x18\x04 \x01(\t\x12\x12\n\nunit_price\x18\x05 \x01(\x01\x32<\n\x03Rfq\x12\x35\n\x03rfq\x12\x16.products.QuoteRequest\x1a\x14.products.QuoteReply\"\x00\x42,\n\x11io.grpc.examples.B\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_QUOTEREQUEST = _descriptor.Descriptor(
  name='QuoteRequest',
  full_name='products.QuoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rfq_id', full_name='products.QuoteRequest.rfq_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acc_id', full_name='products.QuoteRequest.acc_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_num', full_name='products.QuoteRequest.product_num', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_category', full_name='products.QuoteRequest.product_category', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='products.QuoteRequest.quantity', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=139,
)


_QUOTEREPLY = _descriptor.Descriptor(
  name='QuoteReply',
  full_name='products.QuoteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unit_price', full_name='products.QuoteReply.unit_price', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='price_validation_period', full_name='products.QuoteReply.price_validation_period', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=206,
)


_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='products.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_num', full_name='products.Product.product_num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_category', full_name='products.Product.product_category', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='products.Product.quantity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='price_validation_period', full_name='products.Product.price_validation_period', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unit_price', full_name='products.Product.unit_price', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=335,
)

DESCRIPTOR.message_types_by_name['QuoteRequest'] = _QUOTEREQUEST
DESCRIPTOR.message_types_by_name['QuoteReply'] = _QUOTEREPLY
DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuoteRequest = _reflection.GeneratedProtocolMessageType('QuoteRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUOTEREQUEST,
  __module__ = 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.QuoteRequest)
  ))
_sym_db.RegisterMessage(QuoteRequest)

QuoteReply = _reflection.GeneratedProtocolMessageType('QuoteReply', (_message.Message,), dict(
  DESCRIPTOR = _QUOTEREPLY,
  __module__ = 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.QuoteReply)
  ))
_sym_db.RegisterMessage(QuoteReply)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCT,
  __module__ = 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.Product)
  ))
_sym_db.RegisterMessage(Product)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021io.grpc.examples.B\017HelloWorldProtoP\001\242\002\003HLW'))

_RFQ = _descriptor.ServiceDescriptor(
  name='Rfq',
  full_name='products.Rfq',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=337,
  serialized_end=397,
  methods=[
  _descriptor.MethodDescriptor(
    name='rfq',
    full_name='products.Rfq.rfq',
    index=0,
    containing_service=None,
    input_type=_QUOTEREQUEST,
    output_type=_QUOTEREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RFQ)

DESCRIPTOR.services_by_name['Rfq'] = _RFQ

# @@protoc_insertion_point(module_scope)
